server:
  port: 8003
  tomcat: 
    uri-encoding: UTF-8
spring:
  application:
    name: consumer-service-feign
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
      host: localhost
      port: 6379
      password:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.66.77:8000/eureka/,http://192.168.66.77:9000/eureka/
  instance: 
    prefer-ip-address: true
    ip-address: 192.168.66.77
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true