server:
  port: 8002
  tomcat: 
    uri-encoding: UTF-8
spring:
  application:
    name: consumer-service-ribbon
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.66.77:8000/eureka/,http://192.168.66.77:9000/eureka/
  instance: 
    prefer-ip-address: true
    ip-address: 192.168.66.77
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}