spring:
  application:
    name: spring-cloud-eureka
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  port: 9000
  tomcat: 
    uri-encoding: UTF-8
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.66.77
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.66.77:8000/eureka/
    fetch-registry: true  
    register-with-eureka: true
  server:
    enable-self-preservation: false
